# Basics of PyTorch

In [3]:
!pip install torch


[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: C:\Users\Dev Sahu\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [2]:
import torch

### Tensors

In [3]:
t1 = torch.tensor(4.)
t1
t1.dtype

torch.float32

In [4]:
#vector
t2 = torch. tensor([1.,2,3,4])


In [5]:
#matrix
t3 = torch.tensor([[2,4],
                   [6,7]]) # creates a matrix with integer 
print(t3)

t3=torch.tensor([[2,4],
                   [6,7.]]) # creates a matrix with floating values
print(t3)

tensor([[2, 4],
        [6, 7]])
tensor([[2., 4.],
        [6., 7.]])


In [6]:
#3 dimensional matrix
t4 = torch . tensor ([[[11,12,13],[14,15,16]],
                       [[3,4,5],[8,9,0]]]) 

Shape & Dimensions of tensors

In [7]:
print(t4.shape)
print(t4.dim())
print(t4.size())


torch.Size([2, 2, 3])
3
torch.Size([2, 2, 3])


### Arithmetic operations

In [10]:
t4 = torch.tensor([[1. , 2.],[-2 , -3]])
print('t3',t3)
print('t4',t4)


t3 tensor([[2., 4.],
        [6., 7.]])
t4 tensor([[ 1.,  2.],
        [-2., -3.]])


In [ ]:
# t5 = t4+t3
t5 =t4*t3
t5
#element wise multiplications 

tensor([[  2.,   8.],
        [-12., -21.]])

In [19]:
# for creating a tensor in with same values
t6=torch.full((3,3),5)
t6

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

In [16]:
# concatination

t7 = torch.full((3,3),2)
t8 = torch.cat((t6,t7))
t8

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5],
        [2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]])

In [17]:
#reshape
t9 = t8.reshape(3,6)
t9

tensor([[5, 5, 5, 5, 5, 5],
        [5, 5, 5, 2, 2, 2],
        [2, 2, 2, 2, 2, 2]])